- name: yum update
  become_user: root
  yum:
    name: '*'
    state: latest

- name: install general packages
  become_user: root
  yum:
    name: 
      - git
      - make 
      - gcc-c++ 
      - patch 
      - libyaml-devel 
      - libffi-devel 
      - libicu-devel 
      - zlib-devel 
      - readline-devel 
      - libxml2-devel 
      - libxslt-devel 
      - ImageMagick 
      - ImageMagick-devel 
      - openssl-devel 
      - libcurl
      - libcurl-devel
      - curl
    state: installed
