---
version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@4.1.3
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.1.2

jobs:
  provisioning-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: deploy cloudformation
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/VPC.yml --stack-name VPC-Subnets
            aws cloudformation deploy --template-file cloudformation/SecurityGP.yml --stack-name SGsetting --capabilities CAPABILITY_NAMED_IAM
            aws cloudformation deploy --template-file cloudformation/Resorces.yml --stack-name Resorcesetting --capabilities CAPABILITY_IAM
      
  execute-ansible-playbook:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:SsqsNKoSt7e3pCYwueRAD/Y0Nzn6VgRglDxCvPz7sYg"
      - ansible-playbook/install:
          version: 2.10.7
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: '-i ansible/inventory'

  execute-serverspec:
    executor: ruby/default
    steps:
      - checkout
      # サーバーのセットアップ
      - run:
          name: bundle install
          command: |
            cd serverspec
            gem list -e rails
            bundle install --path vendor/bundle

      # Serverspecのテストを実行
      - run:
          name: execute serverspec
          command: |
            cd serverspec
            bundle exec rake spec


workflows:
  version: 2
  provisioning-deploy:
    jobs:
      - provisioning-stack
      - execute-ansible-playbook:
          requires:
            - provisioning-stack
      - execute-serverspec:
          requires:
            - execute-ansible-playbook
            
